plugins {
	id 'java-library'
	id 'maven-publish'
	alias libs.plugins.freefair.lombok
	alias libs.plugins.spring.dependency.management
	id 'jacoco'
}

group = 'fi.poltsi.vempain'
version = project.hasProperty("releaseVersion") ? project.releaseVersion : libs.versions.project.get()

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(libs.versions.java.get().toInteger())
	}
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs += ['-Xlint:deprecation', '-Xlint:unchecked']
}

jar {
	archiveFileName = "vempain-auth-core-${version}.jar"
}

repositories {
	mavenCentral()
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	annotationProcessor libs.lombok
	implementation project(':api')
	implementation libs.spring.boot.starter.security
	implementation libs.spring.boot.starter.webmvc
	implementation libs.spring.boot.starter.data.jpa
	implementation libs.spring.boot.starter.validation
	implementation libs.jjwt.api
	implementation libs.swagger.annotations
	implementation libs.postgresql
	// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
	implementation libs.commons.lang
	testImplementation platform(libs.junit.bom)
	testImplementation libs.junit.jupiter
	testImplementation libs.junit.platform.launcher
	testImplementation libs.spring.boot.starter.test
	testImplementation libs.spring.boot.starter.security.test
	testImplementation libs.spring.boot.starter.webmvc.test
	testImplementation libs.spring.boot.starter.data.jpa.test
	testImplementation libs.spring.boot.starter.validation.test
	testImplementation libs.testcontainers.junit.jupiter
	testImplementation libs.testcontainers.postgresql
	testImplementation libs.spring.boot.starter.flyway
	testImplementation libs.mockito.junit.jupiter
	compileOnly libs.lombok
	runtimeOnly libs.jjwt.impl
	runtimeOnly libs.jjwt.jackson
	runtimeOnly libs.flyway.database.postgresql
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacoco {
	toolVersion = libs.versions.jacoco.get()
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		html.required = true
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifactId = 'vempain-auth-core'
		}
	}
	repositories {
		maven {
			name = "GitHubPackages"
			url = uri("https://maven.pkg.github.com/Vempain/vempain-auth")
			credentials {
				username = System.getenv("GITHUB_ACTOR") ?: project.findProperty("gpr.user") ?: ""
				password = System.getenv("GITHUB_TOKEN") ?: project.findProperty("gpr.token") ?: ""
			}
		}
	}
}
