plugins {
	id 'java-library'
	id 'maven-publish'
	alias libs.plugins.freefair.lombok
	id "jacoco"
}

group = 'fi.poltsi.vempain'
version = project.hasProperty("releaseVersion") ? project.releaseVersion : libs.versions.project.get()

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(libs.versions.java.get().toInteger())
	}
}

jar {
	archiveFileName = "vempain-auth-api-${version}.jar"
}

repositories {
	mavenCentral()
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	api libs.spring.boot.starter.data.jpa
	api libs.spring.boot.starter.webmvc
	implementation libs.swagger.annotations
	implementation libs.spring.boot.starter.validation
	implementation libs.spring.boot.starter.jackson
	testImplementation libs.spring.boot.starter.test
	testImplementation libs.spring.boot.starter.security.test
	testImplementation libs.spring.boot.starter.webmvc.test
	testImplementation libs.spring.boot.starter.data.jpa.test
	testImplementation libs.junit.jupiter
	testImplementation libs.junit.platform.launcher
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifactId = 'vempain-auth-api'
		}
	}
	repositories {
		maven {
			name = "GitHubPackages"
			url = uri("https://maven.pkg.github.com/Vempain/vempain-auth")
			credentials {
				username = System.getenv("GITHUB_ACTOR") ?: project.findProperty("gpr.user") ?: ""
				password = System.getenv("GITHUB_TOKEN") ?: project.findProperty("gpr.token") ?: ""
			}
		}
	}
}

jacoco {
	toolVersion = libs.versions.jacoco.get()
}

tasks.named('test') {
	useJUnitPlatform()
}

test {
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
	}
}
